application: mltest-planets
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /install
  script: install.app

- url: /clima
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: MySQLdb
  version: "latest"
